services:
  frontend:
    build:
      context: ./frontend
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
